name: Build/release
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
        package_manager: [yarn]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # Only install Snapcraft on Ubuntu
          if: startsWith(matrix.os, 'ubuntu')
          with:
              # Log in to Snap Store
              snapcraft_token: ${{ secrets.snapcraft_token }}

          #See Code Signing section for macOS at https://github.com/marketplace/actions/electron-builder-action
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}